### ISSUE TITLE
DragHandler erroneous starting offset

### ISSUE THREAD

**Issue by noncom** [jMonkeyEngine-Contributions/Lemur#64] opened 2018-11-07 20:41 UTC
There is a bug in the `DragHandler` class. The

    basePotition = capture.getWorldTranslation().clone()

line in `startDrag()` should probably instead be 

    basePosition = capture.getLocalTranslation().clone()

because everywhere else the handler is working with the local translation and getting the world translation here introduces an abnormal initial offset on drag start if the spatial is a child of some other spatial and its relative location is not 0, 0, 0.

It is easy to demonstrate this behavior by modifying the `com.simsilica.lemur.demo.BasicDemo` class: replace the line

    guiNode.attachChild( testPanel );

in `simpleInitApp()` with

    Node node = new Node();
    node.attachChild(testPanel);
    node.setLocalTranslation(200, 200, 0);
    guiNode.attachChild(node);

and try to drag the testPanel.

**Comment by pspeed42** [comment] 2018-11-18 10:20
I think the problem is unfortunately more complicated than that.  Dragging is done in world space... so basing dragging on the world space coordinates is correct.  The issue is that the results are not applied in a local-space friendly way.

For example, I think if you rotate your node then things will behave very strangely.  Essentially, DragHandler is not written to properly handle children where local and world translation are not the same.  It could be... but it's more complicated than just basing the starting position on local space.  At least I think.  It's possible some other magic makes it work if node is rotated but I don't think so.

**Comment by pspeed42** [comment] 2018-11-18 22:03
I don't think it requires all that.  I haven't tested it or anything but I believe it's as simple as:
-continue calculating dragging in world space as before
-instead of calling spatial.setLocalTranslation() with the world space coordinate, convert that world space coordinate to local space with spatial.getParent().worldToLocal()

**Comment by pspeed42** [comment] 2018-11-19 00:18
Fix committed and confirmed it works in the demo.  Closing this issue.

**Closed by pspeed42** 2018-11-19 00:18 UTC
